# Generated by Django 2.2.10 on 2021-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210221_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoquestion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
