# Generated by Django 2.2.10 on 2021-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210221_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertoquestion',
            name='answer_options',
            field=models.ManyToManyField(blank=True, to='quiz.AnswerOption'),
        ),
    ]
