# Generated by Django 2.2.10 on 2021-02-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210221_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresponse',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Quiz'),
            preserve_default=False,
        ),
    ]
