# Generated by Django 2.2.16 on 2021-02-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answerresponse_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Question with text answer.'), ('choose_one', 'Question with one choice.'), ('choose_many', 'Question with many choices.')], default='text', max_length=30),
        ),
    ]
